-- Número do chamado.
--
-- Sem ele, referir-se a um card exige descrever o card inteiro ("aquele do print
-- da tela de orçamento"). Com ele, é "resolveu o 14?".
--
-- IDENTITY global, não por organização: a MVF NET é a única org e um contador por
-- org exigiria função + trava contra corrida, o que não se paga para um rótulo.
-- Se um dia houver outra org, os números ficam intercalados — não repetem.
alter table feedback_items
  add column if not exists numero integer generated by default as identity;

create unique index if not exists feedback_items_numero_uniq
  on feedback_items (numero);
